### PR TITLE
Log endpoints

### PR DESCRIPTION
**Pull request by rbocsi**

### CODE REVIEW

**Review by borditamas — APPROVED** [review]
I've found only an unnecesarry empty file
Képkivágás

**Comment by borditamas** [comment]
Sorry, also found in Timemanager and Translator at the same place.

**Comment by rbocsi** [comment]
> I've found only an unnecesarry empty file Képkivágás

It is not unnecessary, this is the banner when the tests are run (so no Spring banners in the test log because of the empty files)

**Comment by borditamas** [comment]
Okay!

**Review by MaGaMeGa — APPROVED** [review]

**Pull request merged**
